### ISSUE TITLE
10 ways to shoot yourself in the foot with kubernetes, #9 will surprise you! (Container Day Paris) 

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kubernetes-failure-stories#21]
Slides: https://www.slideshare.net/lbernail/10-ways-to-shoot-yourself-in-the-foot-with-kubernetes-9-will-surprise-you-container-day-paris

It contains two new incidents (compared to the previous KubeCon talk with the same name): https://twitter.com/lbernail/status/1136207196713357312

**Comment by gugahoi** [comment]
this was a very fun read!

**Comment by hjacobs** [comment]
Moved to https://codeberg.org/hjacobs/kubernetes-failure-stories/issues/4
