### ISSUE TITLE
Sailing with the Istio through the shallow water

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kubernetes-failure-stories#44]
https://twitter.com/learnk8s/status/1221357221893808129:

Istio is not all bells and whistles. Note from a production horror story:

- All pods crashing due to missing labels
- Jobs not completing (sidecar is running forever)
- doesn't update IP for headless Services
- sidecar shuts down before the app does

https://medium.com/@jakubkulich/sailing-with-the-istio-through-the-shallow-water-8ae81668381e

**Comment by NargiT** [comment]
was merged https://github.com/hjacobs/kubernetes-failure-stories/pull/43
